import React from 'react'

function Computers() {
    return (
        <div>
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Architecto accusamus numquam blanditiis alias sequi tempore commodi iusto, repellat fuga modi voluptatibus minus praesentium odit vel velit provident at ut eligendi dolor ullam. Dolorem ullam quisquam mollitia ipsa vel iure et tempora eveniet aut enim ad sapiente esse perferendis, quod iste? Corrupti earum excepturi aspernatur unde doloribus beatae nemo aliquid laborum molestias! Corrupti corporis, saepe soluta ipsam ab perspiciatis est ipsum? Earum sequi reprehenderit aliquid ab, neque in quisquam quaerat alias accusamus totam placeat esse nulla qui, autem reiciendis incidunt possimus ullam minima! Aliquam hic corrupti numquam laudantium, placeat eaque quas enim a accusamus perspiciatis deserunt iure nobis? Nesciunt laudantium libero ea accusamus sint, iste et, illum aut laboriosam porro, quibusdam quaerat vero. Autem libero rerum unde consequatur suscipit, alias cupiditate excepturi. Animi totam dolore, a facilis debitis nesciunt eius, vero explicabo doloremque quae, quos praesentium libero officiis nobis. Quaerat, nulla illum porro qui recusandae earum corrupti assumenda deserunt quisquam, culpa saepe, velit veritatis soluta labore dolores repellat pariatur. Est dolor optio nemo consectetur fuga, explicabo suscipit doloremque temporibus impedit quam ducimus nesciunt? Soluta quasi obcaecati molestiae quidem? Enim recusandae, doloremque error numquam quasi ratione. Libero natus quia aut obcaecati perspiciatis delectus repudiandae omnis? Possimus in maxime iusto quibusdam delectus tempore nihil repellendus deserunt assumenda sint debitis, consectetur temporibus! Nesciunt officia quia quas ducimus deleniti saepe nisi velit iure praesentium blanditiis autem, sapiente quae perferendis quidem aut fugiat repudiandae iste a. Ipsam, in. Labore hic quo nostrum similique esse, veniam eius nulla quos consequuntur sequi illo a architecto porro iste iure facere. Iure alias distinctio modi fugiat amet nostrum, iste voluptatibus magnam, totam, minima illo commodi! Illum ex eligendi aliquid. Fuga fugit, id mollitia natus, doloribus, ipsa quia atque optio tempore maxime blanditiis quasi vel deleniti eaque soluta ad placeat? Eum soluta veritatis enim laudantium ut alias! Assumenda sed architecto culpa! Aspernatur in deserunt aperiam beatae exercitationem! Odit repellendus esse ducimus eos itaque laboriosam porro amet molestias pariatur nobis! Quia officiis delectus saepe dicta accusamus, accusantium est necessitatibus ipsam assumenda dolorum qui animi repellendus veritatis totam consequatur rerum ullam. Omnis, aperiam!
        </div>
    )
}

export default Computers
