import React from 'react'

function GiftCorners() {
    return (
        <div>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis, nihil ipsa! Blanditiis recusandae dicta id quis fugit ipsa eaque nobis earum at, laudantium fuga minus, nisi quos. Vel iure, beatae nulla magnam molestiae voluptatibus numquam. Explicabo quisquam, consectetur placeat unde qui numquam maiores corrupti laudantium. Placeat veniam obcaecati incidunt. Numquam est earum recusandae maiores blanditiis quibusdam sit, sed, ratione placeat natus laborum facere quod aspernatur voluptatum ea aliquid. Quos tenetur, placeat repudiandae repellat quidem consequatur iure voluptas repellendus reprehenderit necessitatibus soluta dolores facilis odit est eum ipsam inventore fuga aliquid error suscipit quibusdam, nulla nihil omnis deserunt! Dolore, maiores architecto ab quia itaque numquam sint rerum illo voluptatem, saepe deleniti rem nam, iure consequuntur veritatis aliquam laboriosam eos excepturi doloremque voluptate soluta. Adipisci nemo cupiditate inventore id, saepe qui, modi molestiae quibusdam rem, quidem reiciendis iusto eos eum? Repellat magni maiores error atque voluptatibus nam enim voluptatem molestias labore. Soluta repellat neque obcaecati qui minima optio reprehenderit ad nihil? Tempora adipisci, fugit corporis temporibus omnis, quidem vero maiores harum accusamus ipsa culpa quo vel. Distinctio cumque et qui impedit aut aspernatur quia quibusdam incidunt, laudantium ipsum iusto iure unde velit blanditiis dicta ad deleniti est aperiam recusandae maxime. Aperiam unde recusandae perferendis molestias, eveniet architecto id repellendus. Totam ut eos, eum tempore fugit soluta delectus facere minima, harum mollitia quisquam sapiente rem natus nihil. Ipsam neque similique consequatur sed placeat repellat quisquam quas non iure ducimus tenetur voluptatem harum vel sit, temporibus earum et natus aperiam amet dolorum. Fuga, in fugiat assumenda debitis accusamus culpa perspiciatis architecto sunt consequatur ipsam dicta vero unde odit? Porro recusandae aperiam dolorem officia eligendi ipsum cum exercitationem vero veritatis voluptas fugiat perferendis, consequuntur nostrum nesciunt. Nulla illo error suscipit exercitationem unde quos magni vero dicta quaerat aliquid. Accusamus, repudiandae. Beatae omnis repellendus nesciunt fugit?
        </div>
    )
}

export default GiftCorners
