import React from 'react'

function KidsWaer() {
    return (
        <div>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quis minus iste atque ea sapiente fuga eaque recusandae rerum molestias dicta tempore aut deserunt ad est necessitatibus quibusdam dolore molestiae eligendi officia expedita, quam adipisci officiis facere laboriosam. Molestiae obcaecati deserunt dicta vel nobis, quas aspernatur! Odio veniam velit officia quae ea quod molestias molestiae porro, reprehenderit dolores quas recusandae debitis nam ut quidem ex doloremque aut beatae, illo laboriosam odit nesciunt excepturi? Aliquid assumenda, hic inventore aliquam consequuntur, deleniti soluta dolorem voluptates totam culpa accusamus eveniet possimus quae ipsa labore. Libero, doloribus molestiae! Quae quidem animi labore dicta soluta minus aut mollitia impedit? Ducimus ullam officiis, dignissimos dolorum ipsum eum? Quod repudiandae pariatur hic eaque quidem quas, voluptatibus tempora qui ex ut dolores ab cumque provident aliquid earum! In iure voluptas natus eveniet dolore itaque vero dignissimos pariatur voluptatibus accusamus temporibus possimus inventore consequuntur repellat molestiae vel, asperiores laborum fugiat officiis minus repudiandae, soluta amet neque nemo! A beatae nisi aperiam modi in, facere voluptatem impedit natus vero temporibus iure dicta, nesciunt necessitatibus maiores illum velit eligendi fugiat. Aut fugit velit, assumenda exercitationem ipsam explicabo dolorum expedita modi odio esse similique facere et laudantium necessitatibus voluptatibus porro dolor praesentium rerum sunt, quae dignissimos ex ipsa blanditiis. Amet nemo necessitatibus iste itaque modi doloremque pariatur inventore culpa, ducimus aliquam minima tempore sit, ipsa voluptatibus quidem reprehenderit. Itaque voluptatum ea similique laudantium illo, laborum eligendi officia. Saepe tempora ipsa ab debitis tempore, sunt mollitia dolores assumenda alias quod recusandae odio blanditiis minima nobis voluptates iure quia eum quisquam sint porro aliquid rem corrupti exercitationem! Voluptas architecto quia harum eveniet fuga ducimus distinctio labore odio blanditiis? Unde, aliquam! Aliquam ipsa doloremque quos ex explicabo eum. Aspernatur blanditiis quis, voluptate nihil tempore dignissimos delectus! Recusandae enim ab ratione, laboriosam molestias sit minima voluptates nisi?
        </div>
    )
}

export default KidsWaer
