import React from 'react'

function Toys() {
    return (
        <div>
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolores quibusdam excepturi mollitia et voluptatum asperiores deserunt doloremque? Corporis perferendis cumque perspiciatis neque nisi, autem pariatur minima mollitia officia tempora magni harum ipsam esse, delectus fugit molestias architecto labore. Corrupti autem officia tempore esse harum repellendus, incidunt doloribus quibusdam quos aperiam vel ad nulla eligendi at maiores eos adipisci facere aspernatur eaque doloremque ipsa praesentium voluptatibus suscipit non? Officiis aperiam earum doloribus deleniti, adipisci nemo! Temporibus, possimus. Illum, velit? Debitis possimus eligendi et aperiam non, ipsa nisi iusto ipsum voluptate facere ratione deserunt laudantium vero, odit iste deleniti, porro sequi magni blanditiis distinctio corrupti reprehenderit nihil aliquid consequatur. Doloribus facere ad alias error quidem fugiat, quae blanditiis officiis excepturi id exercitationem a accusamus dicta! Fuga consequuntur officia magni repellendus ipsum nostrum sit, nemo illo sint perferendis, ducimus reiciendis consequatur tenetur veniam temporibus expedita. Placeat voluptas velit ex quasi sunt voluptate amet eos, dicta nostrum magni ut porro. Repellendus fuga nostrum laboriosam eligendi quos similique officia, architecto assumenda numquam! Id cum at ullam, eligendi doloremque, iusto quis sint eveniet eum voluptatem fuga enim veniam soluta debitis, maxime maiores iste! Ducimus illo nihil nemo voluptatibus vitae expedita autem ipsa? Quia atque alias ea. Voluptatem impedit, quos totam dicta dolorum sequi amet sunt possimus a ullam laborum autem nulla ipsum corrupti, maiores id dolore, perferendis temporibus quod. Amet, asperiores nobis! Aliquid ducimus laboriosam provident fugit mollitia perferendis veniam iure obcaecati doloribus quis amet quae voluptates dolore molestiae a, sunt cumque officiis omnis, deserunt reprehenderit expedita! Corporis modi placeat nihil, vero eveniet earum totam veniam dolorum. Quibusdam recusandae doloribus necessitatibus ducimus unde eaque cumque assumenda, dicta maiores obcaecati qui quo earum exercitationem quos dolor nulla quis perferendis explicabo eligendi inventore autem similique ratione veniam atque. Quae velit ab reprehenderit nobis eligendi dolor sequi tempora maxime.
        </div>
    )
}

export default Toys
